### ISSUE TITLE
Fix Railway Pipeline

### ISSUE THREAD

**Issue by downdrown** [downdrown/vaadin-minicalendar#33]
The railway pipeline does not work as expected and needs to be adapted to work with the new custom Docker image.

**Comment by mstahv** [comment]
I isn't no expert with railway, but deployed a tiny example of your add-on here: https://addons.dokku1.parttio.org/minicalendar

Feel free to use that as an add-on link in the Directory until you get the railway pipeline fixed!

**Comment by downdrown** [comment]
Railway does no longer offer a free plan which means the Railway demo deployment is EOL.
