### ISSUE TITLE
Calendar styling not applied

### ISSUE THREAD

**Issue by fschon** [downdrown/vaadin-minicalendar#37]
Using Vaadin 23.3.32 and 1.3.0 of the minicalendar, the css styling is not applied to the calendar. The minicalendar is added to a layout that is included in a module in the maven build.

![image](https://github.com/downdrown/vaadin-minicalendar/assets/18084317/1741b0dd-a4ff-4759-baa2-1491742e727f)

        MiniCalendar appointmentDatePicker = new MiniCalendar();
        calendarLayout.add(appointmentDatePicker);
        appointmentDatePicker.setValue(activityItem.getAvailableStartDate());
        appointmentDatePicker.addValueChangeListener(event -> {
            updateTimeslotLayout(event.getValue());
        });

**Comment by fschon** [comment]
After some further efforts, I now have the minicalendar styling being applied. The issue was not that the component was in a maven sub module, but rather than the containing element for the minicalendar was a LitElement extended component. Once I recoded my LitElement into a vanilla VerticalLayout, then the styling was applied.

So its seems it is probably a Vaadin issue where the styling is not properly done for LitElements.

**Comment by downdrown** [comment]
Hey @fschon! Glad you could fix your issue.
I didn't do a lot in the Add-On for a while and maybe should invest some time for version upgrades as well.
I'll try to reserve some time to catch up with the latest versions 🚢 

Do you consider your issue as resolved? If so I'd close the issue now and open up another for chores, mainly version upgrades.

**Comment by fschon** [comment]
I assume this is probably a Vaadin issue rather than your component, so we can consider it closed thanks.
